### ISSUE TITLE
Dispatcher: Use batched sends for multiple messages as long as payload fits size restrictions

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AmazonSQS#102]
Like ASB the SQS transport could try to estimate the payload sized then bucket them into multiple buckets of N number of messages that still fit the size restrictions (256 KB) and send them in batches for non isolated dispatches

**Comment by ahofman** [comment]
Sounds reasonable - using [SendMessageBatch](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html) you mean? All messages in a batch go to the same queue, is this a problem?

**Comment by danielmarbach** [comment]
Correct. We'd be splitting based on destination like with ASB.
-- 

Have you tried NServiceBus V6 <https://particular.net/nservicebus-v6> yet?

Learn how to scale applications with microservices and NServiceBus 6
<https://www.pluralsight.com/courses/microservices-nservicebus6-scaling-applications>
.
------------------------------

*Join Udi Dahan's next Advanced Distributed Design Course:*

September 2017 Los Angeles, CA, USA <http://particular.net/adsd>

November 2017 Sydney, Australia <http://particular.net/adsd>
------------------------------

**Comment by VladimirMakaev** [comment]
Any plans to have this feature implemented? We're using NServiceBus currently with RabbitMQ and processing large number of messages. We want to start using NServiceBus with SQS and currently evaluating how it works. We would like to see batching implemented to better scale the publishers.

**Comment by VladimirMakaev** [comment]
Additionally the batching is almost a must for us in case of FIFO queues since there is a harder throttling limitations for those

**Comment by danielmarbach** [comment]
Can you explain what you mean by better scale the publisher? Batching on
the transport layer affects currently only message operations that are done
as part of the same message being handled. Message operations done outside
the message handling pipeline on IMessageSession are single operations by
design.

So on other words you could benefit from batching only if your publisher
does multiple Publish operations on the handler context as a result of a
message being handled.

Do you plan to write such handlers? Or are you looking for batching for
message operations outside the message handling pipeline and if yes can you
explain what you'd like to do?

The biggest benefit of the design is not only latency reduction but also
reduced change of ghost messages within the same handling pipeline

**Comment by VladimirMakaev** [comment]
I see what you mean. My use case is primarily SendOnly endpoint constantly sending large volume of data. In this case I wouldn't benefit from this fix. In most other cases where a receiving endpoint is publishing an event so we have 1 message in and 1 message out.

**Comment by danielmarbach** [comment]
@VladimirMakaev 

We have internally an issue that talks about a scope / context functionality that would enable this. Not only SQS but also Azure Service Bus could benefit from that feature. I hypothetical API could look like

```
await messageSession.Scope(async session =>
{
    await session .Send(new MyMessage { Id = c.Id }, sendOptions);
    await session .Send(new MyMessage { Id = c.Id }, sendOptions);
});

```

all those operations would then be handed over to the transport as one batch and if possible dispatched together as one API call in the underlying layers. If you don't mind I add you as an interested customer to that feature and ping you once we are moving on that front. But that requires a few more changes than enabling batching for SQS.

Assuming we had batching in SQS you could theoretically do the following:

```
await messageSession.SendLocal(new BulkBatchStuff());
```

and then have a handler like

```
class BulkHandler : IHandleMessages<BulkBatchStuff>
{
   public async Task(BulkBatchStuff message, IMessageHandlerContext context)
   {
          await context.Send(new MyMessage { Id = c.Id }, sendOptions);
          await context.Send(new MyMessage { Id = c.Id }, sendOptions);
    }
}

```

would that something you would look into? I'm not sure though how much you'd gain because naturally, SQS operations tend to be very fast and low latency and you'd have an addition Send and Receive latency loop in between. I would first measure if it is not simpler to do simply the following

```
var sendOperations = new List<Task>();
for(usefulNumberOfSendsToNotGetThrottled)
{
   sendOperations.Add(messageSession.Send(new MyMessage { Id = c.Id }));
}
await Task.WhenAll(sendOperations);
```

**Comment by VladimirMakaev** [comment]
Thanks for suggested workarounds. But I'd rather do Native Send as described here https://docs.particular.net/transports/sqs/operations-scripting#native-send-the-native-send-helper-methods-in-c 
Because I have a SendOnly endpoint. But certainly a method that can send a collection of messages would be helpful in the long run. I don't think it makes sense so much to expose that scoping concept to the client unless it gives something more than just batched message sending
