### ISSUE TITLE
Implement latest version check

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.AmazonSQS#1212]
Since only the [latest version of a tool is supported](https://docs.particular.net/nservicebus/tools/), the [NServiceBus.AmazonSQS.CommandLine](https://www.nuget.org/packages/NServiceBus.AmazonSQS.CommandLine) tool should have latest version check functionality like [Particular.AzureTable.Export does](https://github.com/Particular/Particular.AzureTable.Export/blob/20e77bd/src/Particular.AzureTable.Export/ToolVersion.cs#L25).

**Comment by DavidBoike** [comment]
Related issues:

* Azure Service Bus https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/461
* SQS Transport https://github.com/Particular/NServiceBus.AmazonSQS/issues/1212
* SQL Persistence https://github.com/Particular/NServiceBus.Persistence.Sql/issues/853

**Comment by danielmarbach** [comment]
Closing, see the reason mentioned [here](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/461#issuecomment-1290269697)
