### ISSUE TITLE
Renew visibility timeout on messages when processing immediate retries

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#126]
Immediate retries are processed in-memory in a loop; the message is not returned to the queue between each retry. The visibility timeout is not reset between each retry, therefore there is increased chance of messages may become available at the queue while the immediate retries are still processing.

**Comment by mauroservienti** [comment]
@Particular/aws-maintainers thoughts on this?

**Comment by danielmarbach** [comment]
I think we can defer this to the next minor when we address the larger pump refactoring.

**Comment by danielmarbach** [comment]
We rather would allow users to set the visibility timeout to something sensible that takes retries into account in the worst case than increasing the number of broker calls. Closing

As a workaround customers can always disable immediate retries and just do delayed retries with any arbitrary intervals in between
