### ISSUE TITLE
Duplicate events published when scaling out subscribers

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#128]
Affects 1.x releases (for NSB v5).

The ReplyToAddress is given in the form "Endpoint@MachineName". When subscribers are scaled out across multiple machines, Publishers end up with one subscription per machine per subscriber. The publisher publishes one event per subscribing machine, when it should only publish one event per subscribing endpoint. 

Consider using `Address.IgnoreMachineName()` as the Sql transport does.

**Comment by mauroservienti** [comment]
NServiceBus v5 and SQS 1.x are no longer supported. Closing.
