### ISSUE TITLE
Setting the credentials in production

### ISSUE THREAD

**Issue by VenkiMit04** [Particular/NServiceBus.AmazonSQS#129]
Whats the best way to set up the credentials in non-aws production environment? Setting the access and secret key environmental variable is not ideal.

**Comment by VenkiMit04** [comment]
Since AWS SDK is used, wouldn't be good to create SQS client with default parameterless constructor? So the client can set the credentials in all the possible manner AWS sdk supports

**Comment by SimonCropp** [comment]
@VenkiMit04 you can problematically. read a connection string from anywhere and then pass it to `transport.ConnectionString`

```
var transport = busConfiguration.UseTransport<SqsTransport>();
transport.ConnectionString("Region=ap-southeast-2;S3BucketForLargeMessages=myBucketName;S3KeyPrefix=my/key/prefix;");
```

But yes you are correct a strong typed api would be ideal. let me do some research and get back to you

**Comment by chrissimon-au** [comment]
I'll add a +1 on this.  

And to clarify, @SimonCropp  - I believe @VenkiMit04  is referring to the AWS credentials.  These are not specified in the SqsTransport connection string. Rather the connection string permits you to nominate one of 2 sources for the credentials:

* InstanceProfile
* Environment Variables

The Instance Profile options works well for running on AWS EC2 instances, and Environment Variables is acceptable for dev environments, but @VenkiMit04  is talking about non-AWS Production environments.

The AWS SDK permits a large number of transparent methods for configuring the credentials - see http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html.

The Transport (and configuration of the transport) would be simpler if the AWS Client objects were instantiated using the default ctor, permitting the AWS SDK to automatically pick up the credentials from one of the many other sources it permits.  This would be more consistent with most AWS native applications.

It would also permit the Transport connection string to be simpler, as you wouldn't have to nominate a credential source, you could just leave it to the SDK.

**Comment by danielmarbach** [comment]
@Particular/aws-maintainers how about we prioritize this for the next major?

**Comment by mauroservienti** [comment]
agreed

**Comment by danielmarbach** [comment]
@VenkiMit04 @chrissimon-au version 4.0 will allow specifying your own client factory, see https://github.com/Particular/NServiceBus.AmazonSQS/pull/155. By default, we will create the clients with the default constructor but we allow to override the client factory with a delegate. 

Are you guys Ok with closing this?

**Comment by VenkiMit04** [comment]
Yes. We can close thus issue and thank you for working on this.

**Comment by mauroservienti** [comment]
Closing. Feel free to re-open if something is missing.
