### ISSUE TITLE
[Question] Listen to SNS/SQS messages produced by AWS services

### ISSUE THREAD

**Issue by GurGaller** [Particular/NServiceBus.AmazonSQS#1323]
Various AWS services publish events in the form of messages. I'm wondering if there is a way for an NServiceBus endpoint to subscribe to these events without manually managing the subscriptions and deduplication and all the staff that NSB provides.

I guess the main problem is that these messages don't have an NServiceBus ID, but they do carry an identifier. Is there a way to make NServiceBus use that identifier somehow?

In general, how is an integration like this typically implemented (when external systems write messages to the same message transport used by NServiceBus, and we have no control over the format of the messages)?

(I'm not sure if this is the right place to ask this, but it seems relevant as this repository deals with the integration of SNS and SQS to NSB)

**Comment by ramonsmits** [comment]
@GurGaller 

> How can I set the identifier for messages that do not conform to the NServiceBus header specification.

This can be addressed by hooking into the [pipeline](https://docs.particular.net/nservicebus/pipeline/) at a very early stage for example in the `ITransportReceiveContext` or `IIncomingPhysicalMessageContext`. THere you can inspect data on the incoming message and do last minute changes on the data to for example make a message message compatible with the NServiceBus method deserialize to the right type or invoke a handler.

More information available at:

- https://docs.particular.net/transports/sqs/native-integration
- https://docs.particular.net/samples/sqs/native-integration/

> I'm wondering if there is a way for an NServiceBus endpoint to subscribe to these events without manually managing the subscriptions and deduplication and all the staff that NSB provides.

I'm not sure I follow. In any case, this repository isn't mean to address support question. Would you be so kind to continue this via https://particular.net/support ? That page provides several options like our forum to ask question.
