### ISSUE TITLE
Introduce Circuit Breaker when moving poison messages to the error queue

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.AmazonSQS#133]
When poison messages are moved to the error queue, it might happen that the message is successfully sent to the error queue but the subsequent request to delete the incoming message fails causing the message to be handled once more, fail and be moved to the error queue twice or more.

It would be better to let the exception surface and introduce a circuit breaker to handle this scenario.

Source: https://github.com/Particular/NServiceBus.AmazonSQS/blob/develop/src/NServiceBus.AmazonSQS/MessagePump.cs#L327

**Comment by danielmarbach** [comment]
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-limits.html

We can have 120K inflight messages per queue and an unlimited amount of TPS. Not following up with this one

**Comment by mauroservienti** [comment]
Closing as won't fix, as duplicates are by design on SQS and idempotent handlers or the Outbox are required.
