### ISSUE TITLE
Support processing any native message

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AmazonSQS#1454]
Currently, the transport does a number of things like [base64 encoding](https://github.com/Particular/NServiceBus.AmazonSQS/issues/1446) and the [message type header requirement](https://docs.particular.net/transports/sqs/native-integration#message-type-detection) that makes it hard to use native messages. Ideally, we would flip around the requirements and everything that is NServiceBus specific should be additive on top of native messages and not be a requirement.

#### Updated by @DavidBoike August 2, 2023

Version 6.1 allowed [sending and receiving content that is not Base64-encoded](https://github.com/Particular/NServiceBus.AmazonSQS/issues/1446), and in doing so loosened up the restrictions on messages that NServiceBus can process, but did not go all the way to full native message suport.

For full native message support, the transport should be able to send any message that makes it to an SQS through to the NServiceBus pipeline, including infrastructure messages like SNS notifications from the SES service, or a notification that a file was uploaded to an S3 bucket.

In these cases, the message type will likely not be known, by default processing will fail in the NServiceBus pipeline at the connector from physical to logical message, because without a known message type, deserialization will fail. It would require the endpoint to register a behavior to make sense of the native message and modify the physical message so that the logical message can be deserialized. But currently the SQS transport does not give the pipeline the opportunity to do this.

Due to the Base64 legacy handling as well as storage of large message bodies in S3, the SQS message pump is more complex than most, so accomplishing this may require a few different strategies:

* First, assume all incoming messages are probably NServiceBus messages and look for the telltale headers that should be present in such cases.
* If all these attributes are missing, then the message body may be a Base64-encoded message envelope, or it could be a native message.
* It will likely be necessary to attempt deserializing the body as a Base64 envelope, and if that fails, the exception should be caught and the message still passed to the pipeline.
* It may be advantageous from a performance perspective to inspect the first few bytes of the body to see if the body _looks like_ Base64 text. If the first character is a `{` then clearly that is not the case and the message is probably a native JSON-encoded message.

**Comment by mikesigs** [comment]
We have several non-NSB SQS queues (wired up via SNS topic subscription) and we would love to be able to directly tap into these queues via SQS Transport. Currently we have our own custom SQS polling mechanism that pulls the messages out of SQS and puts them into another queue managed by SQL Transport. It's obviously not ideal to have two queues joined like this, and would love to just be able to leverage the SQS queue and transport directly.

**Comment by efleming18** [comment]
Same as @mikesigs for me. Being able to leverage the SQS queue and transport directly will unlock many great capabilities for us. Looking forward to seeing what updates can be made here.

**Comment by danielmarbach** [comment]
@mikesigs @efleming18 We have started working on this and will keep you posted once it is available

**Comment by jpalac** [comment]
This has been improved in [release 6.1.0](https://github.com/Particular/NServiceBus.AmazonSQS/releases/tag/6.1.0)

**Comment by danielmarbach** [comment]
There are still [some restrictions](https://docs.particular.net/transports/sqs/native-integration#message-type-detection) when it comes to what is required / assumed to be an a native message to make it possible to handle it properly on an endpoint. For that reason, we are keeping the issue open.
