### ISSUE TITLE
SNS integration for publishing and trigger event based AWS Lambda Function

### ISSUE THREAD

**Issue by gpiccinni** [Particular/NServiceBus.AmazonSQS#147]
Hi,
since AWS supports .NET core for AWS Lambda Function it would be nice to publish the event to SNS being able to trigger Lambda Function to process the message (see the image below).
![sns-sqs](https://user-images.githubusercontent.com/9968586/30886798-c901a87e-a318-11e7-9b01-157196e466a0.png)
Do you think it is possible to update the code to include a publish on SNS topic (_optional_) together with SQS insertion to trigger the Lambda? 

Thanks.
G

**Comment by danielmarbach** [comment]
Sounds like a neat idea. Still wondering if it makes sense to have it as part of the same code base or if this should be using an extension point of NServiceBus to plug the behavior in.

**Comment by mikeminutillo** [comment]
@gpiccinni I have just pushed a sample which shows how to hook into the Dispatch context of the NServiceBus pipeline and take action after a dispatch operation. 

I think this would enable you to easily build what you are describing. All you would need is the code to send the SNS topic. 

It's worth noting that this notification can be called multiple times for the same transport operation if there is a problem with finishing the processing on the incoming message. If you're using the Outbox pattern, then at least these duplicates will have deterministic ids. It's just something to be aware of when building the lambda function.

You can see the sample here https://github.com/Particular/docs.particular.net/pull/3291

Take a look and see if that's enough to get you moving.

**Comment by danielmarbach** [comment]
@gpiccinni @mikeminutillo sample is merged and available under https://docs.particular.net/samples/pipeline/dispatch-notifications/. I hope this gets you moving. In the meantime, I'll close the issue. Feel free to reopen if you'd like to discuss it more.
