### ISSUE TITLE
Why does Region have a default?

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AmazonSQS#150]
Why does Region have a default? You will need to call quite a lot of API's anyway so why not also region?

**Comment by danielmarbach** [comment]
@ramonsmits I just double checked we are not explicitly setting the region default. Will do some further investigation and come back to you with an answer

**Comment by mauroservienti** [comment]
It's set only in the acceptance tests

**Comment by danielmarbach** [comment]
I [updated the readme](https://github.com/Particular/NServiceBus.AmazonSQS/commit/8be6974ff99cb00830e427069940acd841b1568f) to remove the wrong default. The doco states it correctly

> Region
> Mandatory
> Default: None.

https://docs.particular.net/transports/sqs/configuration-options?version=sqs_4#region
