### ISSUE TITLE
Queue names are case sensitive, should NServiceBus enforce lowercase queues?

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AmazonSQS#151]
Queue names are case sensitive:

- http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html

Should NServiceBus make queue names lower-case so if customers would use different casing in their endpoint addresses that messages will be able to be delivered to the expected queues?

**Comment by SimonCropp** [comment]
given this is a breaking change how would we introduce it?

**Comment by danielmarbach** [comment]
On the fence about changing it. Part of the SQS ecosystem is that queues are case-sensitive. So why should we behave differently? The option I see if we see value in it is to introduce an optional flag that lower-cases all queues

**Comment by mauroservienti** [comment]
I'm 👎 to hiding the SQS behavior, it seems very similar to "I want a compiler that makes all my variables case insensitive ala-vb", thanks, but no thanks 😃

**Comment by danielmarbach** [comment]
Agree with @mauroservienti. Thanks for raising this @ramonsmits. Closing

**Comment by SimonCropp** [comment]
one minor follow up. do we need to call this out in doco?

**Comment by mauroservienti** [comment]
I'd say yes @SimonCropp, which is the best place to document that?

* https://docs.particular.net/transports/sqs/configuration-options
* https://docs.particular.net/transports/sqs/

**Comment by danielmarbach** [comment]
@SimonCropp I remember you saying that we try to avoid documenting platform specific things if we can.

**Comment by SimonCropp** [comment]
@danielmarbach we do. but given we are providing an abstraction to that "platform specific thing" i am wondering if a one line note would be worthwhile?

**Comment by ramonsmits** [comment]
Does this mean our routing is also case sensitive?

**Comment by danielmarbach** [comment]
As far as I know, there is nothing in the routing that does change the entries done by the users. So I'd say it is case sensitive as well. @SzymonPobiega can you maybe clarify?

**Comment by SzymonPobiega** [comment]
I don't recall anything that would make routing case insensitive. Some of the transports are though i.e. when translating from the logical address to transport address they lowercase everything.

**Comment by danielmarbach** [comment]
Routing should be able to deal with it. closing
