### ISSUE TITLE
How to deal with rate limiting?

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AmazonSQS#152]
It seems that with AmazonSQS you can easily be rate limited. How should a user deal with this?

I've looked at the message pump but that doesn't have any backoff logic:

- https://github.com/Particular/NServiceBus.AmazonSQS/blob/develop/src/NServiceBus.AmazonSQS/MessagePump.cs

Should the message pump have a backoff policy?

**Comment by danielmarbach** [comment]
I'm pretty sure one of the problems that causes this behavior is #132

**Comment by ramonsmits** [comment]
@danielmarbach That seems to be about the message pump. If you have max concurrency set to 1 you can still have this issue but yes, maybe it can also be because the message pump fetches messagse too aggressively resulting in rate limiting exceptions.

**Comment by danielmarbach** [comment]
Ideally, there should be a backoff policy similar to what ASQ is doing. I think we can address this in the v5 timeframe when we address the pump refactoring

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/NServiceBus.AmazonSQS/issues/156. Closing

**Comment by ramonsmits** [comment]
I thought the rate limit was happening during receive but that isn't the case. It is during the bulk seeding. I had set the max concurrency to 128 and didn't have any issue during the receives.

It is only an issue on AmazonSQS 4.x, 3.0.0 does not have this issue.

The rate limit also kicks in immediately:

* https://www.youtube.com/watch?v=BAyWSMUYfsU&feature=youtu.be
* [local.log](https://github.com/Particular/NServiceBus.AmazonSQS/files/1394545/local.log)

The essential lines are:

```
2017-10-18 12:12:15.4500|INFO|11|BaseRunner|Start seeding messages for 101.75 seconds until 10/18/2017 14:13:57...
2017-10-18 12:12:15.7670|ERROR|19|NServiceBus.Transports.SQS.MessageDispatcher|Exception from Send.
Amazon.SQS.AmazonSQSException: Request is throttled. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
```
It is almost instantly.

**Comment by ramonsmits** [comment]
If I seed using the regular approach to do bulk sends it works:

```c#
Task Chunk(int size)
{
    var tasks = new List<Task>(size);
    for(int i=0;i<size;i++) tasks.Add(session.SendLocal(new Message));
    return  Task.WhenAll(tasks);
}

await Chunk(100000).ConfigureAwait(false);
```

It fails when I do:

```c#
Parallel.ForEach(IterateUntilFalse(() => !cts.Token.IsCancellationRequested), new ParallelOptions { MaxDegreeOfParallelism = 4 },  b => {
    Chunk(10000).GetAwaiter().GetResult()
});
```

**Comment by danielmarbach** [comment]
@ramonsmits is this an unbounded enumerable?

Is it a typo that the first approach uses `size = 100 000` and the other uses `size = 10 000`?

**Comment by ramonsmits** [comment]
No, not a type although my sample isn't entirely clear, the second would do chunks of 10,000 in parallel, the following would be a better example:
```c#
Parallel.ForEach(Enumerable.Range(1,10), new ParallelOptions { MaxDegreeOfParallelism = 4 }, b =>
{
    Chunk(10000).GetAwaiter().GetResult();
});
```

**Comment by mauroservienti** [comment]
Closing as per https://github.com/Particular/NServiceBus.AmazonSQS/issues/156#issuecomment-492221828
