### ISSUE TITLE
Bus.Transports.SQS.SqsDequeueStrategy|Couldn't delete message body from S3 (NServiceBus 5)

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AmazonSQS#167]
I got the following exception while (performance) testing V5:

> 2017-11-15 00:08:42,122|WARN|118|NServiceBus.Transports.SQS.SqsDequeueStrategy|Couldn't delete message body from S3 because the SqsTransportMessage was null. Message body data will be aged out by the S3 lifecycle policy when the TTL expires.

I'm not sure why this happens and I cannot find any docs on it but it seems to maybe happen for every message received.

Connection string used:
```
Region=eu-west-2;QueueNamePrefix=ramon-perftest-;S3BucketForLargeMessages=ramon-perftest-sqs;S3KeyPrefix=messages;MaxTTLDays=1"
```

**Comment by danielmarbach** [comment]
@ramonsmits did you see the following message as well?

> Treating message with SQS Message Id {message.MessageId} as a poison message because it could not be converted to an IncomingMessage. Moving to error queue.

**Comment by ramonsmits** [comment]
@danielmarbach I don't know, I would have to rerun the tests. What is the log level? It it wasn't a Warning I probably not seen it.
