### ISSUE TITLE
Startup check that throws when platform not Windows

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AmazonSQS#169]
Relates to https://github.com/Particular/DotNetCoreLaunch/issues/100

#168  turned out to be an AWS SDK bug that manifests itself under .NET Core under Linux. Since until this is fixed we cannot support .NET Core under any other OS than Windows a startup check should be implemented that throws when the runtime platform is not windows.

**Comment by danielmarbach** [comment]
@yvesgoeleven will help out

**Comment by danielmarbach** [comment]
Fixed with https://github.com/Particular/NServiceBus.AmazonSQS/pull/172. Closing

**Comment by yvesgoeleven** [comment]
@danielmarbach will push the button ;)

**Comment by danielmarbach** [comment]
I did now mit 🤣
