### ISSUE TITLE
Command line flaky test

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.AmazonSQS#1693]
`Remove_large_message_support_from_endpoint_removes_bucket_with_remove_shared_resources`

**Comment by danielmarbach** [comment]
Haven't seen this one failing so far. Let's keep an eye on it, but maybe we can close it?

**Comment by danielmarbach** [comment]
Discussed this today and we decided to close it for now. We can always reopen should the problems occur again.

**Comment by danielmarbach** [comment]
Failed again https://github.com/Particular/NServiceBus.AmazonSQS/actions/runs/4116296415

**Comment by mauroservienti** [comment]
And again https://github.com/Particular/NServiceBus.AmazonSQS/actions/runs/4121563826
