### ISSUE TITLE
Flaky test: Should_route_commands_correctly

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.AmazonSQS#1698]
[Should_route_commands_correctly: _1/nservicebus.acceptancetests.sources/8.0.0-rc.3/contentFiles/cs/net472/NSB.AcceptanceTests/Routing/When_using_custom_routing_strategy.cs#L21](https://github.com/Particular/NServiceBus.AmazonSQS/pull/1696/files#annotation_5599289383)

> System.Exception : Delayed delivery queue 'ATXGPLVQRO70EBYOR39UCG7WUsingCustomRoutingStrategy-Receiver-delay.fifo' has a Delivery Delay of '00:00:00'. It should be less than '00:15:00'.

**Comment by danielmarbach** [comment]
We looked at the core test and figured it the problem could come from the metadata of the queue being eventually consistent as well as using optimistic concurrency. The queue creator code currently did create the queue and then set the delay. We have now collapsed the creation and the delay setting into one operation, potentially making this problem less likely to occur.
