### ISSUE TITLE
Check that all required AWS permissions are granted at startup

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#17]
This should be done for v2 in the StartupChecks in TransportInfrastructure.

The required permissions are listed here: https://docs.particular.net/transports/sqs/#getting-started-set-up-an-aws-account

**Comment by ahofman** [comment]
This requires granting new permissions to the transport - it at least needs read-only permissions on IAM. This may not be palatable.

**Comment by mauroservienti** [comment]
We decided that it's not acceptable to require new permissions to check existing permissions. Closing as won't fix.
