### ISSUE TITLE
Graceful shutdown seems to take way too long if the endpoint is and/or just was under load

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AmazonSQS#171]
During performance testing I noticed that triggering a stop can take a while. I cannot really say how long but it is noticeably slower than other transports.

However, it does shutdown gracefully, so there is no real issue.

**Comment by danielmarbach** [comment]
Improved as part of https://github.com/Particular/NServiceBus.AmazonSQS/pull/175 Closing
