### ISSUE TITLE
Error messages when configuration is bad are not helpful

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.AmazonSQS#187]
e.g. when SQS is configured properly but S3 is not user gets an exception that does not mention where the problem is like "Region or ServiceURL is not configured"

**Comment by mauroservienti** [comment]
Are you testing latest beta (`develop`) or RTM from `master`?

**Comment by SzymonPobiega** [comment]
@mauroservienti I used `4.0.0-beta0007` in end-to-end transport compat tests. I have copied the code over from V3, which seems to only require one line config:

```
transportExtensions.Region("us-east-1");
```

When upgraded I got a hint that the `Region` method is obsolete and I should provide a client instance. So I added the following code:

```
transportExtensions.ClientFactory(() => new AmazonSQSClient(new AmazonSQSConfig
                {
                    RegionEndpoint = RegionEndpoint.USEast1
                }));
```

And it reacted with the mentioned exception. So I started debugging and looked at the S3 SDK code and it seemed like everything is fine. Only later I found out that the same exception is thrown when validating the `AmazonS3Config`.

Ultimately I solved this by adding

```
transportExtensions.S3("transport-compat-tests", "TCC").ClientFactory(() => new AmazonS3Client(new AmazonS3Config
                {
                    RegionEndpoint = RegionEndpoint.USEast1
                }));
```

but for a new user it is by no means obvious, especially that I did not get an exception saying that S3 is not configured so I expected it to be optional.

I think the root problem is the fact that if I don't provide a client factory then a new instance of a client is created using a no-arg ctror so it is guaranteed to fail the validation of region/service URL.

**Comment by danielmarbach** [comment]
@mauroservienti let's discuss on monday. The obsoletion method should hint
env variable first and only for advanced scenarios client factory overload.
The question is do we always need to create the S3Client and can we
properly safe guard the client creation. I see ways to improve this

Am 05.01.2018 12:09 schrieb "Szymon Pobiega" <notifications@github.com>:
