### ISSUE TITLE
Should `.ConnectionString(...)` be supported?

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AmazonSQS#188]
Related to https://github.com/Particular/NServiceBus.AmazonSQS/issues/129

The transport does not support `.ConnectionString(...)` since connection relevant information is read from environment variables by default or advanced connection information can be passed in using the provided client factory overloads. Should connection string be supported?

**Comment by SeanFeldman** [comment]
Is there a concept of "connection string" for SQS or it's something arbitrary we'd come up with?
Does it mean taking the values and mapping to `AmazonSQSConfig`?
Newbie questions 🙂

**Comment by danielmarbach** [comment]
> Does it mean taking the values and mapping to AmazonSQSConfig
Correctly summarized.

**Comment by SeanFeldman** [comment]
I can think of two points in favour of having a connection string

1. Standardized way of specifying all information needed to establish a connection. While it's might not be so valuable in many scenarios, it's convenient in the cases where configuration is read as a whole and used as-is.
1. Consistent API from NServiceBus point of view. Specifically for SQS customers dealing with the native client on AWS it might not much of a value, but for anyone coming to NServiceBus first and then picking a transport it's an easy abstraction that flows from one transport to another.

**Comment by SeanFeldman** [comment]
One aspect I've not thought about, and was reminded about, is the possibility of AWS SQS client introducing a connection string down the road. We'll then end up with 2 formats (NServiceBus specific format and SQS native format) and will be forced to deal with connection strings parsing business. Which is not ideal.

**Comment by danielmarbach** [comment]
Acces Key Id and Secret are something global to all services used by a user that owns that token. So if the IAM sets the appropriate right multiple services can be used, for example, S3 and SQS or even other services. This means the token and secret are not something that belongs as information into the connection string. Same applies to the region. I see no valid reason why you'd want to connect from the same container or environment to multiple regions and services running in multiple regions. Taking this into account what information would we want to put into the connection string?

**Comment by SeanFeldman** [comment]
Now I'm even more convinced that we **should not** invent something that doesn't exist. 🔥 the idea 🙂

**Comment by danielmarbach** [comment]
Closing this based on https://github.com/Particular/NServiceBus.AmazonSQS/issues/188#issuecomment-356729963
