### ISSUE TITLE
Should we use SimpleJson for the transport envelope serialization and deserialization

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AmazonSQS#189]
This would allow us to get rid of the newtonsoft json dependency.

We would need to check the backward compliance from SimpleJson and NewtonsoftJson but it looks like it should be possible because the envelope is a really simple and lightweight data type.

**Comment by SeanFeldman** [comment]
Doesn't have to be rushed, could be next major release, but having no dependency and internalize this concern would be a 👍.

**Comment by SzymonPobiega** [comment]
I agree that getting rid of newtonsoft is desirable. The SC plugins migrated from the data contract serialization to SimpleJson in the latest edition. The SQLT still uses the data contract serializer. Sounds like a good candidate for a maintenance release.

**Comment by danielmarbach** [comment]
Merged #286. Closing
