### ISSUE TITLE
Requires windows?

### ISSUE THREAD

**Issue by ChrisEvansUM** [Particular/NServiceBus.AmazonSQS#195]
Hi,

As of the latest package we're running into an exception on startup when using linux containers:

NServiceBus.AmazonSQS/src/NServiceBus.AmazonSQS/Configure/RequiresWindows.cs

Have you got any more info on what the bug in AWS is and what impact this causes please?

Kind Regards,

Chris

**Comment by danielmarbach** [comment]
Hi Chris,

Further details can be found in 

https://github.com/Particular/NServiceBus.AmazonSQS/issues/168

and the link AWS SDK issue

https://github.com/aws/aws-sdk-net/issues/796

Hope that helps

**Comment by SeanFeldman** [comment]
The restriction to run on windows has been lifted in version 4 beta8.
