### ISSUE TITLE
Default region is suboptimal as it doesn’t support (yet) FIFO queues

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.AmazonSQS#199]
If no region is set via environment variables the transport defaults to `ap-southeast-2` that doesn’t FIFO queues (yet) making the new delayed deliveries unusable.

https://github.com/Particular/NServiceBus.AmazonSQS/blob/c1aeca485d0b6abfc55055dead296af03a45ac64/src/AcceptanceTests/SqsTransportExtensions.cs#L41

https://github.com/Particular/NServiceBus.AmazonSQS/blob/c1aeca485d0b6abfc55055dead296af03a45ac64/src/AcceptanceTests/SqsTransportExtensions.cs#L46

**Comment by danielmarbach** [comment]
That default doesn't make sense IMHO and should go anyway. I wonder also if
we shouldn't just switch to AWS_REGION instead if using custom variable for
the ATTs

Am 06.03.2018 21:58 schrieb "Mauro Servienti" <notifications@github.com>:

**Comment by danielmarbach** [comment]
We are no longer using the default region. Closing
