### ISSUE TITLE
Transport throws incorrect exception

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AmazonSQS#201]
When arguments passed in by users are guarded, an incorrect exception is thrown.

Example:

```c#
transportConfiguration.QueueNamePrefix("")
```

Throws 
```
System.ArgumentNullException : Value cannot be null.
Parameter name: queueNamePrefix
```

which is misleading as parameter is not null. This is caused by `Guard.AgainstNullAndEmpty`
throwing `ArgumentNullException` exception.
https://github.com/Particular/NServiceBus.AmazonSQS/blob/03cc82b80f3511cf24447029ba5e42a7e80f1ec0/src/NServiceBus.AmazonSQS/Guard.cs#L19

### Expected behaviour

Either correct exception is thrown or empty string is accepted as a valid queue prefix.

**Comment by danielmarbach** [comment]
I did a quick check across all the repositories and the guard implementation we use there is standard across all repositories that use this guard. I share your opinion the exception is not entirely perfect but changing this would probably require us to align across the repos and change the guards in all of those. I don't see much value in this honestly. Closing for now
