### ISSUE TITLE
Finish SNS batch publishing support

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/NServiceBus.AmazonSQS#2020]
The message dispatcher has been restructured to allow SNS batch publishing but the actual batching implementation is not yet complete.

## Goals

- Finish the SNS batch publishing changes
- Optional: Release a patch version in case the small task time permits

## Recommended skills

- Knowledge of SQS / SNS and the AWSD SDK is required
- Familiarity with the SQS transport dispatcher is a plus

## Plan of action

- [x] Finish the implementation in https://github.com/Particular/NServiceBus.AmazonSQS/pull/2003
- [x] Review and merge
- [x] Optionally: Follow the release process to release a patch version of the transport with the new changes

**Comment by danielmarbach** [comment]
Implemented and released as part of 6.1.1

https://discuss.particular.net/t/nservicebus-amazonsqs-6-1-1-patch-release-available/3507
