### ISSUE TITLE
Wire-compatibility issue between NSB5 (SQS Transport 1.3.1) and NSB 6 (SQS Transport 2.x/3.x)

### ISSUE THREAD

**Issue by chrissimon-au** [Particular/NServiceBus.AmazonSQS#213]
In v1.3.1, the SQS Transport had a transport message property `TimeToBeReceived`.  It seems that in SQS Transport 2.x / 3.x, this has been moved to a standard NSB header.

This breaks wire-compatibility:

1.3.1 has logic that assumes that a message is expired and is to be discarded if the `TimeToBeReceived` header is not equal to `TimeSpan.MaxValue` - which is won't be if it's not present.  See https://github.com/Particular/NServiceBus.AmazonSQS/blob/hotfix-1.3.1/src/NServiceBus.AmazonSQS/SqsDequeueStrategy.cs#L168.

(Even worse, there is a bug in the discard approach: it does not delete the message from the queue, so the message becomes a poison message that is infinitely re-received and released back to the queue.)

This impacts on an upgrade pathway - we had been assuming that we could upgrade endpoints to NSB6 one-by-one in any sequence and rely on wire-protocol compatibility to ensure interoperation between NSB5 and NSB6 endpoints.  This issue means that messages can flow from NSB5 endpoints -> NSB6 endpoints, but not from NSB6 endpoints -> NSB5. (And even then, only if `TimeToBeReceived` is not a required feature).

While we could adjust our upgrade plans to accommodate the necessary sequencing of upgrade, it would be great if this could be addressed with an update to the transport - either by having v3.x add `TimeToBeReceived` onto the transport message (perhaps as an optional config option) or by releasing a 1.3.x update to make it forward compatible with the new wire protocol.

Thanks!

**Comment by mauroservienti** [comment]
@Particular/aws-maintainers does this qualify as a `patch`?

**Comment by mauroservienti** [comment]
@chrissimon-au thanks for reporting this, and sorry for the the pain we're causing. We'll investigate options and get back to you soon.

**Comment by chrissimon-au** [comment]
No problem - for what it's worth, I agree with the design decision to move the `TimeToBeReceived` property to a header - it's not an SQS-specific property, and it makes sense that the `SqsTransportMessage` would only have properties specific to transporting over SQS.

It's just a shame about the backwards compatibility implications!

**Comment by chrissimon-au** [comment]
For anyone who comes across this issue and needs a workaround, we've found one which appears to solve this problem for now without requiring any changes to the transport.  Because the transport uses the direct `JsonConvert.Serialize` method, it's possible to hook into JSON.Net's serialization configuration to cause the missing `TimeToBeReceived` property to be serialized.

Configuring the following JSON.Net contract resolver and value provider into the NSB6 (SQS 3.2) endpoint, will add a `TimeToBeReceived` property with `TimeSpan.MaxValue` to the serialized message.  Our testing indicates that NSB5 (SQS 1.3.1) endpoints can now properly process these messages.  Since we are just using a hard coded TimeSpan.MaxValue, this breaks support for the actual TimeToBeReceived functionality, but we don't need that in our application.

We use a string comparison on the Sqs TransportMessage type name because the type is internal so we can't easily do a type comparison.

```c#
    internal class BackwardsCompatibleSqsTransportContractResolver : DefaultContractResolver
    {
        private const string FullyQualifiedTypeName = "NServiceBus.AmazonSQS.TransportMessage";

        protected override IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)
        {
            var properties = base.CreateProperties(type, memberSerialization);
            if (type != null && type.FullName == FullyQualifiedTypeName)
            {
                properties.Add(TimeToBeReceivedValueProvider.TimeToBeReceivedProperty(type));
            }
            return properties;
        }        
    }
```

```c#
    internal class TimeToBeReceivedValueProvider : IValueProvider
    {

        private const string PropertyName = "TimeToBeReceived";
        private readonly string _propertyValue = TimeSpan.MaxValue.ToString();

        private TimeToBeReceivedValueProvider()
        {

        }

        public void SetValue(object target, object value)
        {

        }

        public object GetValue(object target)
        {
            return _propertyValue;
        }

        public static JsonProperty TimeToBeReceivedProperty(Type type) => new JsonProperty
        {
            PropertyName = PropertyName,
            ValueProvider = new TimeToBeReceivedValueProvider(),
            ShouldSerialize = o => true,
            ShouldDeserialize = o => false,
            DeclaringType = type,
            PropertyType = typeof(string),
            Readable = true,
            Writable = false,
            UnderlyingName = PropertyName,

        };

    }
```

To activate the contract resolver:

```c#
    JsonConvert.DefaultSettings = () => new JsonSerializerSettings
    {
        ContractResolver = new BackwardsCompatibleSqsTransportContractResolver()
    };
```

**Comment by boblangley** [comment]
@chrissimon-au Version 3.3.0 has been released that includes a backwards compatibility feature to include the `TimeToBeReceived` and `ReplyToAddress` properties in the message envelope for endpoints using 1.x of the transport.

Thank you for bringing this to our attention.

https://www.nuget.org/packages/NServiceBus.AmazonSQS/3.3.0
