### ISSUE TITLE
The QueueNameGenerator API might be misleading

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.AmazonSQS#2314]
#### Is your improvement related to a problem? Please describe.

The `QueueNameGenerator` API accepts a function of two arguments, the queue prefix and the queue name, and returns the final queue name with added prefix. The transport code assumes this function is idempotent i.e. that it can detect that a given queue name already has prefix and in that case skip applying it again. This fact is not documented which may lead to problems when trying to use the API.

On the flip side, the default queue name generator uses simple `Substring` to check if the prefix has already been applied leading to problems if the configured prefix is a substring of an endpoint name e.g. when prefix is `Prod` (denoting environment) and the endpoint name is `ProductionProcessControl`. In that scenario the correct queue name is `ProdProductionProcessControl` but the actual result is going to be `ProductionProcessControl`.

#### Describe the suggested solution

- Document the limitations of the API
- Introduce a two-part addressing scheme similar to MSMQ or SQL Server transports where the transport address includes both prefix and the queue name (delimited)

### Additional Context

Similar issue _might_ be affecting the `TopicNameGenerator` API (but it has not been verified)

**Comment by mauroservienti** [comment]
This has been improved in https://github.com/Particular/NServiceBus.AmazonSQS/pull/2342. The transport at startup exercises the QueueNameGenerator API twice with the same values and validates the result is the same; otherwise, it throws.
