### ISSUE TITLE
Bundle queues creation scripts within the transport package

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.AmazonSQS#238]
Other than providing [documentation on scripts to manage SQS queues](https://docs.particular.net/transports/sqs/operations-scripting), in light of better supporting DevOps oriented teams we should bundle queues creation scripts, as the [MSMQ Transport does](https://github.com/Particular/NServiceBus.Transport.Msmq/tree/develop/src/NServiceBus.Transport.Msmq/Scripts) for example.

**Comment by lailabougria** [comment]
Discussed this with the TF and Mauro and we already have most scenario's covered with the Amazon SQS command-line tool.
