### ISSUE TITLE
Delete unsupported branches

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.AmazonSQS#245]
@Particular/aws-maintainers can you please delete all support branches which are no longer supported so TC won't try to build them anymore? I don't have permissions to do this myself.
the list of supported versions can be found here: https://docs.particular.net/nservicebus/upgrades/supported-versions#transport-packages-nservicebus-amazonsqs

**Comment by danielmarbach** [comment]
Already done
