### ISSUE TITLE
Not possible to use storage alternative using S3 API

### ISSUE THREAD

**Issue by petarvu** [Particular/NServiceBus.AmazonSQS#2495]
### Describe the feature.

Tried to use Cloudflare R2, but it requires setting the `DisablePayloadSigning = true` .

![image](https://github.com/Particular/NServiceBus.AmazonSQS/assets/2004480/c7b83282-5b5f-410e-be0e-4de716a59392)

Info: https://developers.cloudflare.com/r2/examples/aws/aws-sdk-net/#upload-and-retrieve-objects

**Comment by petarvu** [comment]
Hi @NChaganlal 

Cloudflare R2 supports the S3 API, so it should be plug&play solution.

I managed to get it (almost) to work. But it fails on uploads as the payload signing is not supported by R2.

Compelling reason is the price and 0 egress charges :) https://r2-calculator.cloudflare.com/

**Comment by NChaganlal** [comment]
Hi @petarvu I've raised this issue as a separate feature request with some tweaks on wording. Feel free to subscribe to this [GitHub issue](https://github.com/Particular/NServiceBus.AmazonSQS/issues/2498) and track progress on this request. I'll be closing this issue - Thank you!
