### ISSUE TITLE
Amazon SQS transport doesn't support binary serialization

### ISSUE THREAD

**Issue by lailabougria** [Particular/NServiceBus.AmazonSQS#2630]
Currently, NServiceBus supports [Json, XML and System.Text.Json serializers](https://docs.particular.net/nservicebus/serialization/) by default. However, it should also be possible to use a [custom serializer](https://docs.particular.net/nservicebus/serialization/custom-serializer).

#### Expected behavior

Plugging in a custom binary serializer should work without issues, allowing the deserialization of incoming messages and serialization of outgoing messages.

#### Actual behavior

Currently, any binary serialization mechanism would cause the transport to throw when ingesting messages, with the following exception:

`Amazon.SQS.Model.InvalidMessageContentsException: Invalid binary character '#x1' was found in the message body, the set of allowed characters is #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF].`

### Steps to reproduce

- Plug in a custom binary serializer
- Attempt to ingest messages that are serialized with a binary serializer

#### Workarounds

Use a different serialization mechanism.

#### Possible solutions

This was solved for [ServiceControl metrics messages](https://github.com/Particular/NServiceBus.AmazonSQS/issues/2520), so a similar fix may be possible. Ideally, the headers would also include the encoding type in addition to the [content type](https://docs.particular.net/nservicebus/messaging/headers#serialization-headers-nservicebus-contenttype), allowing the transport to identify the encoding type to enable correct deserialization without guessing.

**Comment by mauroservienti** [comment]
It should be possible to leverage the [Base64.IsValid](https://learn.microsoft.com/en-us/dotnet/api/system.buffers.text.base64.isvalid?view=net-9.0#system-buffers-text-base64-isvalid(system-readonlyspan((system-byte))-system-int32@)) method to check the incoming raw payload. There might be the need to backport the method implementation to older framework version, if we need to support them.

**Comment by andreasohlund** [comment]
Fixed in https://github.com/Particular/NServiceBus.AmazonSQS/pull/2646
