### ISSUE TITLE
Create NServiceBus.Cloudwatch package

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#28]

**Comment by ahofman** [comment]
Can be done with the CloudWatch API. Powershell samples here: https://aws.amazon.com/code/7932034889155460

This is probably best done as a separate package, so that users can have the option to use cloudwatch with other transports

**Comment by mauroservienti** [comment]
Closing as duplicate of https://github.com/Particular/NServiceBus.AmazonSQS/issues/244
