### ISSUE TITLE
SQS Transport stops receiving messages after AWS connectivity failure

### ISSUE THREAD

**Issue by staylr** [Particular/NServiceBus.AmazonSQS#296]
We had a connectivity failure from our EC2 instances to Amazon services earlier today. Our NServiceBus processes (hosted as Windows services in NServiceBus.Host.exe) stopped processing messages, and did not resume processing until they were restarted. We're not doing any specific SQS Client configuration in our NServiceBus endpoint configuration.

Is this somehow related to https://github.com/aws/aws-sdk-net/issues/796? I see you had a message there that wasn't received until the next run.

NServiceBus.dll: 6.3.6
NServiceBus.AmazonSQS.dll: 3.1.0
AWSSDK.SQS.dll: 3.3.3.11
AWSSDK.Core.dll: 3.3.24.3

AWS Exception (most hosts did not log anything):
Amazon.Runtime.AmazonServiceException: A WebException with status ConnectFailure was thrown. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.119.211.92:443\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)\r\n   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.SQS.Internal.ValidationResponseHandler.<InvokeAsync>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at Amazon.Runtime.Internal.WebExceptionHandler.HandleException(IExecutionContext executionContext, WebException exception)\r\n   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)\r\n   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.Transports.SQS.MessageDispatcher.<SendMessage>d__3.MoveNext()

Event log:
The description for Event ID 3714 from source awsagent cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

2019-04-30 06:58:41 AM:00007ea0:Error:..\Publishers\ArsenalPublisher.cpp:702:RequestConfig Connectivity failure : Unable to connect to endpoint

**Comment by staylr** [comment]
Not .NET, but maybe relevant?
[https://github.com/aws/aws-sdk-js/issues/367](url)

**Comment by andreasohlund** [comment]
A bit of a wild guess but since you are on v6 the default action for critical errors is to stop the endpoint but keep the process running

https://docs.particular.net/nservicebus/hosting/critical-errors?version=core_6

In v7 this was changed to retry definitely. To get the same behaviour in v6 you would have to use https://docs.particular.net/nservicebus/hosting/critical-errors?version=core_6#custom-handling-a-possible-custom-implementation and just make it a no-op.

Could that be it?

**Comment by staylr** [comment]
I would expect to see log messages in that case.

**Comment by andreasohlund** [comment]
Yes you would at least see a FATAL from NServiceBus 

https://github.com/Particular/NServiceBus/blob/support-6.5/src/NServiceBus.Core/CriticalError/CriticalError.cs#L47

Can you dump all the logs for this timeframe into a textfile so that we can take a deeper look?

**Comment by staylr** [comment]
The ones attached to the first post are all we have, which is weird (server is not out of disk space).

**Comment by andreasohlund** [comment]
Ok, that sounds like a few messages failed during the outage, that's why you see `NServiceBus.Transports.SQS.MessageDispatcher` being mentioned in the log. But then it seems like the outage cause the message pump to get disconnected from the SQS service without detecting it and it took a restart to reconnect it?

https://github.com/Particular/NServiceBus.AmazonSQS/blob/support-3.3/src/NServiceBus.AmazonSQS/MessagePump.cs#L92

**Comment by staylr** [comment]
Yes. Most of our hosts would have been idle, they just silently failed to reconnect when messages arrived on their queue after the outage.

**Comment by andreasohlund** [comment]
I'll talk to some internal experts and see if there are more places we can look, I'll get back to you.

A few related notes:

* [Version 3.1.0 is no longer supported]( https://docs.particular.net/nservicebus/upgrades/supported-versions#transport-packages-nservicebus-amazonsqs). I looked at the change logs and nothing seems to have been fixed that seems to be related to this but if the leads to something we need to fix we would only release that into a 3.3.X version so you might want to start planning for an upgrade. Going from 3.1 to 3.3 should be completely safe since we follow SemVer
* I saw now that you are using the NServiceBus.Host so [my initial statement around critical error behaviour](https://github.com/Particular/NServiceBus.AmazonSQS/issues/296#issuecomment-487866986)  was incorrect since the host will bring the process down if there are critical errors reported from the message pump. Since your endpoints were still running this shouldn't have been the case.

**Comment by staylr** [comment]
Thanks, we've already upgraded to 3.3.x in our development branch to pick up another fix, but that hasn't gone through to production yet.

**Comment by staylr** [comment]
I suspect this is because the AWS SDK uses HttpWebRequest under the hood, and the timeout properties are ignored for async requests, so the requests will never time out when the other party to the TCP connection vanishes.

[https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.timeout?redirectedfrom=MSDN&view=netframework-4.8#System_Net_HttpWebRequest_Timeout ](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.timeout?redirectedfrom=MSDN&view=netframework-4.8#System_Net_HttpWebRequest_Timeout )
 `` In the case of asynchronous requests, the client application implements its own time-out mechanism. Refer to the example in the BeginGetResponse method. ``

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/ClientConfig.cs
     ``  
        /// Overrides the default request timeout value.
        /// This field does not impact *Async calls. A manual timeout (for instance, using CancellationToken) must be implemented.
     ``

The value of WaitTimeSeconds on the sqsClient.ReceiveMessageAsync request appears to be only handled server side.

**Comment by danielmarbach** [comment]
We did some investigations and the latest AWSSDK.Core versions have this behavior fixed. When then did a simple binary search down the different versions starting from your one and figured that the AWSSDK.Core 3.3.28.1 fixes it.

You can verify it by using our Simple SQS example available at https://docs.particular.net/samples/sqs/simple/?version=sqs_3

change the package references to

```
    <PackageReference Include="AWSSDK.Core" Version="3.3.28.1" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.9" />
    <PackageReference Include="AWSSDK.SQS" Version="3.3.2.7" />
```

Change the code to this


```
using System;
using System.Threading.Tasks;
using NServiceBus;

class Program
{
    static async Task Main()
    {
        Console.Title = "Samples.Sqs.Simple";
        var endpointConfiguration = new EndpointConfiguration("Samples.Sqs.Simple");
        var transport = endpointConfiguration.UseTransport<SqsTransport>();

        endpointConfiguration.SendFailedMessagesTo("error");
        endpointConfiguration.EnableInstallers();
        endpointConfiguration.UsePersistence<InMemoryPersistence>();

        var endpointInstance = await Endpoint.Start(endpointConfiguration)
            .ConfigureAwait(false);

        Console.ReadLine();
        var myMessage = new MyMessage();
        await endpointInstance.SendLocal(myMessage)
            .ConfigureAwait(false);

        Console.WriteLine("Disconnect the cable");
        Console.ReadLine();
        await Task.Delay(TimeSpan.FromSeconds(30));
        Console.WriteLine("Reconnect the cable");
        Console.ReadLine();
        myMessage = new MyMessage();
        await endpointInstance.SendLocal(myMessage)
            .ConfigureAwait(false);

        Console.WriteLine("Press any key to exit");
        Console.ReadKey();
        await endpointInstance.Stop()
            .ConfigureAwait(false);
    }
}
```

We will probably bump the minimum required version to 3.3.28.1 in the 3.3.x hotfix that we are about to release to fix this once and for all

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/NServiceBus.AmazonSQS/pull/302

**Comment by andreasohlund** [comment]
[v3.3.5](https://discuss.particular.net/t/nservicebus-amazonsqs-4-3-2-4-2-3-3-3-5-critical-patch-releases-available/1124) bumps the minimum AWSSDK.Core version to prevent this from happening

Closing this, please reopen if the problem occurs after you have updated the sdk version

**Comment by staylr** [comment]
It looks like 30 seconds isn't long enough. I can reproduce the original behaviour (only one "Hello from MyHandler") with AWS SDK 3.3.105.3 leaving the cable disconnected for ~5 minutes, and with disconnecting for only 30 seconds 3.3.24.3 works. Looking through the SDK code I can't see anything that would have fixed this problem. The documentation is pretty clear - you need to implement the cancellation timeout yourself for async calls.

**Comment by staylr** [comment]
@andreasohlund, don't have permissions to reopen this myself.

**Comment by danielmarbach** [comment]
That's interesting because in our tests we could not get it working again
on the 24 version but it did on the 30 version. Weird.

Yes the documentation is clear. The thing is thought while we might be able
to have linked cancelation token source for the receive the documentation
would indicate it would need to be added to every SDK call. Which is pretty
much a no go and then we need to push this back to the SDK team.

The problem gets worse because the code would be only needed for the full
framework version while the netcore version uses HttpClient with a default
timeout of 100 seconds.

Wrapping ReceiveAsync with a linked source with a timeout of 100 seconds
for example might solve the receive blocking but any other API call at any
time could hang indefinitely again

Happy to reopen this and analyze it further

**Comment by staylr** [comment]
Yes, looks like there might be something environment specific going on. Unless you know of something specific that changed in the SDK to fix this I'm not comfortable calling this closed. I'll agree that this should be handled in the SDK.

Also, just found this: https://github.com/aws/aws-sdk-net/issues/609

**Comment by andreasohlund** [comment]
>Unless you know of something specific that changed in the SDK to fix this I'm not comfortable calling this closed. I'll agree that this should be handled in the SDK.

Agreed, we'll discuss this internally and see if we can raise something with the AWS team. We'll keep this issue open to track the discussion.

I guess migrating to netcore isn't an option for you?(you would have to switch to your own host https://docs.particular.net/nservicebus/dotnet-templates#nservicebus-windows-service, which isn't a big deal though)

**Comment by staylr** [comment]
Sorry, netcore is not an option.

**Comment by danielmarbach** [comment]
Raised

https://github.com/aws/aws-sdk-net/issues/1275
https://github.com/aws/aws-sdk-net/pull/1276

**Comment by staylr** [comment]
FYI I've raised an AWS support ticket about the lack of response on this. AWS Support say someone should look at the pull request "this week".

**Comment by danielmarbach** [comment]
Changes have been merged to AWS.SDK.Core and are released. I do think we should consider locking into that version in the next maintenance release of the transport but for now you should just be able to bump your dependencies
