### ISSUE TITLE
Maximum message batch size calculation is incorrect, causing consistent failures when processing messages that result in multiple and/or large outgoing messages

### ISSUE THREAD

**Issue by rafalkozik** [Particular/NServiceBus.AmazonSQS#318]
### Symptoms

Processing of a message that results in sending out multiple large messages consistently fails part-way through. Some outgoing messages are dispatched to the broker but some are not. The message being processed is returned back to its queue and re-processed. Each processing attempt fails with the same problem (assuming processing logic is deterministic), eventually leading to moving that message to the error queue.

Retrying the message from ServiceControl does not solve the problem. The symptoms of the issue include:
- message not being processed on time
- duplicate messages being generated

### Who's affected

All users of SQS transport are potentially affected but the likelihood of the problem actually occurring depends on the number and size of messages being sent. 

### Root cause

The batch size calculation is wrong, leading NServiceBus to send a batch that exceeds the maximum size allowed by SQS. The batch size calculation does not take into account the message attributes.

### Original issue description

I have received exception after completion of the event handler on sending messages to SQS. There is S3 bucket configured for large messages. I've seen this issue only once out of 7 millions of messages processed by the endpoint.

NServiceBus.AmazonSQS: 4.3.4
AWSSDK.SQS: 3.3.3.10

`Amazon.SQS.Model.BatchRequestTooLongException: Batch requests cannot be longer than 262144 bytes. You have sent 262154 bytes. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler``1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at NServiceBus.Transports.SQS.MessageDispatcher.SendBatch(BatchEntry batch, Int32 batchNumber, Int32 totalBatches)
   at NServiceBus.Transports.SQS.MessageDispatcher.DispatchBatched(IEnumerable``1 toBeBatchedTransportOperations)
   at NServiceBus.Transports.SQS.MessageDispatcher.Dispatch(TransportOperations outgoingMessages, TransportTransaction transaction, ContextBag context)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.Invoke(ITransportReceiveContext context, Func``2 next)
   at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext)
   at NServiceBus.Transports.SQS.MessagePump.ProcessMessageWithInMemoryRetries(Dictionary``2 headers, String nativeMessageId, Byte[] body, CancellationToken token)`

Let me know if any additional details are required for the investigation.

**Comment by kbaley** [comment]
Hi @rafalkozik. At first glance, it looks like this may be a bug in how we calculate the message size. When you say it happened once out of 7 million messages processed, does that mean you sent 7 million messages to be processed one time, or that you sent 7 million messages over time and this only happened once?

**Comment by rafalkozik** [comment]
Second case -- endpoint processed 7 million messages in about two weeks and this happened only once.

**Comment by rafalkozik** [comment]
Found the reason https://docs.aws.amazon.com/en_pv/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html -- attributes are included 256 KB limit and code in this package looks only at body size.

Currently there are two places: MessageDispatcher and MessagePump -- both use NServiceBus.MessageId or NServiceBus.AmazonSQS.DelaySeconds (based on situation). Unfortunately those headers are added after decision if body needs to be saved into S3.

I see two options for solving this issue:
1) Simple one: reducing TransportConfiguration.MaximumMessageSize to reserve some space towards those attributes. MessageId seems to use 63 bytes (attribute name + type + guid as string), my proposal is to reserve 128 bytes (PR created)
2) Complicated one: move decision about saving body into S3 after real attributes are already known, requires refactoring

**Comment by danielmarbach** [comment]
Great brainstorming! Another approach could be to only change the batcher
to take into account the attributes added on dispatch plus an additional
attribute in case of delayed delivery. I think this would be OK given that
the pump code today assumes that no special handling of the body is
required because messages arriving in the pump adhere to the size
restrictions or the body is on S3 even when delayed again natively. While
this approach makes assumptions as well I think it is a bit more future
proof in case we add more attributes in the future and the dispatcher has
all the knowledge to make meaningful decisions

rafalkozik <notifications@github.com> schrieb am Sa., 5. Okt. 2019, 18:14:

**Comment by rafalkozik** [comment]
Adjusting batcher seems more future proof, the only problem is that decision about moving stuff to S3 happen earlier. 

Limit for moving body to S3 needs to be lower than one used by Batcher to leave some space for attributes. Any proposals? I'm happy to adjust my pull request with updated functionality.

**Comment by danielmarbach** [comment]
What do you think about this approach? https://github.com/Particular/NServiceBus.AmazonSQS/pull/322

**Comment by rafalkozik** [comment]
Definitely better than mine, especially that my reserved capacity was off and should be multiplied by the maximum number of messages in batch. This is another proof that mine solution was far from perfect.

If MessagePump handles all messages produced by MessageDispatcher within transport constraints then it should be fine. Is space for additional delayed delivery attribute required?

**Comment by SzymonPobiega** [comment]
@rafalkozik I hope you don't mind me updating the issue description with information about symptoms and root case and moving your original content to a separate section.

We recognized this issue as a high priority and labeled it accordingly. We will ping you once we start working on the patch.

**Comment by danielmarbach** [comment]
> If MessagePump handles all messages produced by MessageDispatcher within transport constraints then it should be fine. Is space for additional delayed delivery attribute required?

@rafalkozik the dispatcher adds the `TransportHeaders.DelaySeconds` to the message attributes of the prepared message, see https://github.com/Particular/NServiceBus.AmazonSQS/blob/attributes-contribute-to-size/src/NServiceBus.AmazonSQS/MessageDispatcher.cs#L225. Given that the calculation takes now all message attributes into account we should be fine right?

**Comment by rafalkozik** [comment]
In _MessageDispatcher_ , if _delayLongerThanConfiguredDelayedDeliveryQueueDelayTime_, then there is only _Delay_ attribute, otherwise there is _MessageId_ attribute.

In _MessagePump_, _Delay_ attribute is changed (or skipped), but as _Delay_ goes down, string representation of it has the same or smaller length, so this path should be fine. When remaining delay is small enough, _MessageId_ is not added anymore, so this behavior is not consistent with _MessageDispatcher_, but does not increase size of the message.

In _MovePoisonMessageToErrorQueue_ _MessageId_ attribute is added and it seems that there is a tiny chance that this might end up bigger than expected.

**Comment by danielmarbach** [comment]
I do think we can change the code to always add the `MessageId` in a consistent fashion in the dispatcher. We added the `MessageId` as part of a customer request for easier tracing just over the message attributes. I think (but do not know for sure) that the `MessageId` header was not added for the delayed deliver fifo path because the MessageId is already present as part of the deduplication mechanism. But for safety and precaution when we always add the message id to the attributes we can make sure the Move to Poison message case is also properly handled and overall it makes the behavior more consistent without causing much harm.

**Comment by danielmarbach** [comment]
@rafalkozik we started working on this and will release patches to all supported versions in the next few days.

**Comment by danielmarbach** [comment]
@rafalkozik this is released as part of 4.3.5, see https://discuss.particular.net/t/nservicebus-amazonsqs-4-3-5-patch-release-available/1470

Thanks again for the contribution and helpful input on this one!
