### ISSUE TITLE
Ability to send messages to queues owned by a different account

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AmazonSQS#496]
Originated from discussion in https://github.com/Particular/NServiceBus.AmazonSQS/issues/433

If command routing could be extended with an account id assuming proper setup of IAM would allow the transport sending commands to queues owned by a different account

```
transport.Routing(typeof(ISpecificCommand), "endpoint-b", ownerAwsAccountId = "234234324")
```

**Comment by mauroservienti** [comment]
Closed in favor of https://github.com/Particular/NServiceBus.AmazonSQS/issues/2365
