### ISSUE TITLE
Support for the 3.5 SDK range

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AmazonSQS#549]
Support the 3.5 SDK range

Also related to https://github.com/Particular/docs.particular.net/pull/4973

**Comment by danielmarbach** [comment]
Policy object and everything surrounding it are obsolete and need a complete revamp by potentially copying the necessary structures into the project and then use the already available simple json serializer to read and write policies to the server.

**Comment by voroninp** [comment]
@danielmarbach , Does it mean SDK 3.5 contains breaking changes from 3.4?

**Comment by danielmarbach** [comment]
For us yes because we used the SDK policy objects which are obsoleted

**Comment by voroninp** [comment]
@danielmarbach Were these policy objects removed in 3.5?

**Comment by danielmarbach** [comment]
Well obsolete with WARN in 3.5 so technically we could still be using those with warning supressions

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Auth/AccessControlPolicy/Policy.cs#L71-L73

**Comment by buvinghausen** [comment]
@danielmarbach do you have an ETA on when this might be resolved?  Amazon just dropped v2 on a lot of their packages like SSM and Serilog but they depend on the 3.5.x SDK.

**Comment by danielmarbach** [comment]
@buvinghausen From an SDK perspective, the current situation is very confusing. I've raised an issue that hopefully will be addressed by them. As a temporary measure, we are going to release a new minor version of the transport that supports the 3.5 range by suppressing the policy usage warnings. See https://github.com/Particular/NServiceBus.AmazonSQS/pull/578

**Comment by danielmarbach** [comment]
We've released a 5.2.0 that targets the 3.5 range of the SDK

https://discuss.particular.net/t/nservicebus-amazonsqs-5-2-0-minor-release-available/2140
