### ISSUE TITLE
Poison message in case of OutOfMemory exception

### ISSUE THREAD

**Issue by rafalkozik** [Particular/NServiceBus.AmazonSQS#582]
We have noticed that we have messages on the error queue that are not being loaded into Service Control. After checking the details, it seems that messages were considered as poison messages by [FailedMessageFactory.cs](https://github.com/Particular/ServiceControl/blob/5163de59031cfea1fbd31e4352b8af0375c9ef53/src/ServiceControl/Operations/FailedMessageFactory.cs).

We have confirmed that indeed, this happened via [InputQueuePump.cs](https://github.com/Particular/NServiceBus.AmazonSQS/blob/7efdcb264357c86cafc07b4671d340d714d2270b/src/NServiceBus.Transport.SQS/InputQueuePump.cs)

From our logs we can see that we got _OutOfMemoryException_ during deserialization. Message was moved to error queue as poison message and as it's not being loaded to SC, we cannot retry it from the UI. Any ideas how to deal with this? We'll make sure that we do everything that we can to reduce chance of _OutOfMemoryException_, but would be good to know if there are any good practices for dealing with this scenario.

I'm not sure if change inside of _InputQueuePump.cs_ to handle _OutOfMemoryException_ differently would help, I suspect that real poison message could also cause it.

**Comment by danielmarbach** [comment]
@rafalkozik Is the problem that the [`FaultsHeaderKeys.FailedQ`](https://github.com/Particular/ServiceControl/blob/5163de59031cfea1fbd31e4352b8af0375c9ef53/src/ServiceControl/Operations/FailedMessageFactory.cs#L39) is missing in case of `OutOfMemoryException`?

ServiceControl should move that message to disk

https://docs.particular.net/servicecontrol/import-failed-messages

you should be able to manually edit the file on disk with the necessary missing information and then reimport the message into ServiceControl

**Comment by rafalkozik** [comment]
Yes, it looks that _FaultsHeaderKeys.FailedQ_ won't be added as message failed to deserialize because of _OutOfMemory_ exception.

This is situation that we can easily recover from on the application level, but it looks that there is a lot of manual work involved to reimport messages failed at that time.

After thinking about it for a while, it seems that the nicest solution might be to load those messages into Service Control, but require _AddressOfFailingEndpoint_ update via UI / command line before allowing retry.

**Comment by danielmarbach** [comment]
@rafalkozik we allow messages to be edit if they are imported

https://docs.particular.net/servicepulse/intro-editing-messages

the problem is though in your case the messages can't even be imported. So once you fixed and reimported the messages you can tweak it to your needs using the editing messages feature
