### ISSUE TITLE
Test under high load; measure performance

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#67]

**Comment by ramonsmits** [comment]
Added implementation for the v4 (core 7) to the performance tests:

- https://github.com/Particular/EndToEnd/pull/258

As mentioned on Slack you will get a throttling error pretty fast:

> 2017-10-08 18:46:10.7806|ERROR|44|NServiceBus.Transports.SQS.MessageDispatcher|Exception from Send.
>Amazon.SQS.AmazonSQSException: Request is throttled. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.

**Comment by danielmarbach** [comment]
We have done a series of load testing in the past as well as optimized the pump quite a bit. Closing for now
