### ISSUE TITLE
AWS SDK 3.7 Support

### ISSUE THREAD

**Issue by buvinghausen** [Particular/NServiceBus.AmazonSQS#719]
[AWS SDK 3.7 dropped last night](https://www.nuget.org/packages/AWSSDK.Core/3.7.0)

**Comment by danielmarbach** [comment]
@buvinghausen We have already bumped master and things are looking good. Do you need anything specific from the SDK? 

Normally, we would pick this up as part of the next enhancement release but if you have specific needs to get this early in your hands, please tell us and we can see what we can do

**Comment by buvinghausen** [comment]
@danielmarbach ok cool I didn't realize you already had bumped master I probably should have checked I just noticed when we updated to the latest version your version constraint put down the blocker so I wanted to make sure it was in the pipeline.  Carry on I will close this now.
