### ISSUE TITLE
Add support for SQS Server Side Encryption

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#72]
Add support for Server Side Encryption.
https://aws.amazon.com/blogs/aws/new-server-side-encryption-for-amazon-simple-queue-service-sqs/

- [ ] Add configuration option for enabling SSE on all queues, with a CMK 
- [ ] Update required permissions in docs

**Comment by mauroservienti** [comment]
this is already supported by:

- manually creating queues
- overloading the creation of the client so to provide a custom SQS Client configured to use CMK
