### ISSUE TITLE
SqsQueueCreator should first check if the required resources already exist

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#74]
Some users have reported that they trigger an AWS Lambda function when the queues are created - the Lambda is triggered every time the endpoint starts, regardless of if the queue already exists or not. 

Should do the same check for the S3 bucket, and any other resources that are created during queue creation.

**Comment by danielmarbach** [comment]
With scale-out endpoints and installers enable there is nothing we can prevent from happening. The suggested workaround is to disable installers and manually create queues
