### ISSUE TITLE
Conflict when upgrading from 4.3.4 to 5.3.1

### ISSUE THREAD

**Issue by Selimmo** [Particular/NServiceBus.AmazonSQS#770]
Hi 
we have been trying to upgrade our services to use 5.3.1 to have the SQS/SNS Native subscription style instead of MessageDriven. 
we are doing that by upgrading one service at a time, this means upgraded services will use 5.3.1 whilst non upgraded will use 4.3.4 on the same environment, we just wanted to play this safe because we have many services and the change is kinda big.

we are enabling the EnableMessageDrivenPubSubCompatibilityMode() to make these services work with each others smoothly till all of them are upgraded then we gonna remove the compatibility mode.

Now when a service A using NServiceBus.AmazonSQS version 4.3.4 Publishes an Event that Service B uses 5.3.1 is interested in, we get this exception 
`The specified queue does not exist for this wsdl version.`
The only reason i see is the class 
`QueueNameHelper` specifically `GetSqsQueueName` line 16, it always adds the queueNamePrefix to the destination, which is already there and that's why we end up with this exception or so i guess.

but if we look at 5.3.1, the code actually plays it safe there and makes sure first if the queueNamePrefix is there before adding it. 

So, what am proposing is to add a new version 4.5.0 which supports the same technique followed in 5.3.1 whilst retrieving the queueName, then we can use that version on non upgraded services temporarily while we migrate all.

(I am happy to open a PR)

**Comment by Selimmo** [comment]
Thanks @danielmarbach just wondering when should we expect this to be released ?

**Comment by danielmarbach** [comment]
@Selimmo if everything goes smooth today. I'll keep you posted

**Comment by danielmarbach** [comment]
@Selimmo it is out

https://discuss.particular.net/t/nservicebus-amazonsqs-4-4-2-patch-release-available/2382/1

Thanks for your patience

**Comment by Selimmo** [comment]
Thanks @danielmarbach really appreciate your fast response to this
