### ISSUE TITLE
After update to the last version AmazonSQSException  Submitted policy is over max allowed size

### ISSUE THREAD

**Issue by lillo42** [Particular/NServiceBus.AmazonSQS#830]
Hi,

After update to the last version of NServiceBus I'm getting this error:
AmazonSQSClient 129\|2021-05-20T14:29:56.879Z\|ERROR\|AmazonSQSException making request SetQueueAttributesRequest to https://sqs.eu-west-1.amazonaws.com/. Attempt 1. --> Amazon.SQS.AmazonSQSException: Submitted policy is over max allowed size.

NServiceBus 7.2.0 -> 7.4.6
NServiceBus.Serilog 7.0.0 -> 7.13.1
NServiceBus.AmazonSQS 4.4.0 -> 5.3.1
AWSSDK.SQS 3.3.103.24 -> 3.5.1.28

This is my configuration, Am I missing something?
```c#
var bucketName = "dummy-large-messages";
var transport = endpointConfiguration.UseTransport<SqsTransport>()
                        .ClientFactory(() => new AmazonSQSClient(new AmazonSQSConfig
                        {
                            RegionEndpoint = RegionEndpoint.EUWest1,
                        }));
transport.UnrestrictedDurationDelayedDelivery();
transport.S3(bucketName, "dummy")
            .ClientFactory(() => new AmazonS3Client(new AmazonS3Config
            {
                RegionEndpoint = RegionEndpoint.EUWest1,
            }));        

var routing = transport.Routing();
routing.RouteToEndpoint(typeof(Order).Assembly, "dummy-bus");

var compatMode = transport.EnableMessageDrivenPubSubCompatibilityMode();

compatMode.RegisterPublisher(typeof(Order).Assembly,  "dummy-bus");
compatMode.RegisterPublisher(typeof(Order).Assembly,  "dummy-bus-2");
                
routing.RouteToEndpoint(typeof(SendRazorEmail).Assembly, "dummy-bus-3");
compatMode.RegisterPublisher(typeof(SendRazorEmail).Assembly, "dummy-bus-3");
compatMode.RegisterPublisher(typeof(SendRazorEmail).Assembly, dummy-bus");
compatMode.RegisterPublisher(typeof(SendRazorEmail).Assembly,  "dummy-bus-2");
```

**Comment by mauroservienti** [comment]
Hi @lillo42,

thanks for raising this and sorry for the inconvenience. It's a known issue caused by the fact that the transport cannot create a concise policy and when using auto-subscribe has to create quite a verbose one. For this reason, we recently introduced [policy manipulation](https://docs.particular.net/transports/sqs/configuration-options#policy) support. let me know if that helps.

More details in [this blog post](https://particular.net/blog/amazon-sqs-native-integration-and-iam-policy-management).

**Comment by lillo42** [comment]
After I made what was on the post, start to work thank you :)

**Comment by mauroservienti** [comment]
Thanks for the feedback, I'm glad the issue was solved.
