### ISSUE TITLE
Investigate consistency of S3, confirm suitability for large messages

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#89]
S3 supports read-after-writes consistency in some but not all regions. 

What happens if 

1. Large message is written to s3 by sender
2. message is sent to sqs by sender
3. receiver dequeues message from sqs
4. receiver reads large message from s3, but the read is eventually consistent and returns no data

Does this scenario apply in regions with read-after-writes support?
Does the transport cope with this scenario?

**Comment by danielmarbach** [comment]
From the doco

> Amazon S3 provides read-after-write consistency for PUTS of new objects in your S3 bucket in all regions with one caveat. The caveat is that if you make a HEAD or GET request to the key name (to find if the object exists) before creating the object, Amazon S3 provides eventual consistency for read-after-write.

Given that senders only do PUT and receivers GET we are fine. Closing
