### ISSUE TITLE
Add a startup check to ensure the configured S3 bucket is accessible

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#95]
Names of S3 buckets must be globally unique within a region. Once the name of an S3 bucket is taken by one account, another account cannot create a bucket with the same name. 

Add a startup check to make sure that the name of the configured s3 bucket isn't already taken in that region by another account. 

Note it doesn't matter if the configured bucket doesn't exist yet, as the transport will attempt to create it.

**Comment by VladimirMakaev** [comment]
Please consider this #239 before implementing :)

**Comment by mauroservienti** [comment]
Closing as won't fix. If the endpoint is run without using `EnableInstallers` the S3 bucket won't be created at the endpoint will fail. If the bucket is misconfigured the endpoint will fail in consuming messages that will end up in the error queue.
