### ISSUE TITLE
Test failing if not run in isolation

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.AmazonSQS#97]
I'm running AT locally using remote queues in Frankfurt and a S3 bucket. The `When_publishing_to_scaled_out_subscribers.Each_event_should_be_delivered_to_single_instance_of_each_subscriber` timeouts when run with other tests:

> Test Name:	Each_event_should_be_delivered_to_single_instance_of_each_subscriber
Test FullName:	NServiceBus.AcceptanceTests.Routing.MessageDrivenSubscriptions.When_publishing_to_scaled_out_subscribers.Each_event_should_be_delivered_to_single_instance_of_each_subscriber
Test Source:	C:\dev\ahofman\NServiceBus.AmazonSQS\src\NServiceBus.AmazonSQS.AcceptanceTests\App_Packages\NSB.AcceptanceTests.6.3.4\Routing\MessageDrivenSubscriptions\When_publishing_to_scaled_out_subscribers.cs : line 13
Test Outcome:	Failed
Test Duration:	0:01:20,789

If run with the debugger attached it works, when run in isolation most of the times, but not every time, it works, when run with other AT it always fails

**Comment by danielmarbach** [comment]
With the debugger attached, there is no test timeout. Without the debugger attached the timeout defined in the Configure class will be used which is 20 seconds.

**Comment by ahofman** [comment]
Works fine for me locally whether I run all ATs together or one at a time. I wonder what your connectivity to the Frankfurt region is like - if it's intermittent then the AWS SDK will do a lot of backing off when it retries - [up to 30 seconds!](https://github.com/aws/aws-sdk-net/blob/cfa2b60d98bda61249e320f7c849790e9f8e4f00/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/DefaultRetryPolicy.cs) - which may make the tests time out. 

@mauroservienti could you try increasing the timeout in the `Configure` class to something greater, say 60 seconds, and see if that AT still fails when running with other ATs for you? If that fixes it maybe we need to make the test timeout configurable?

**Comment by mauroservienti** [comment]
Reinstalled OS and tools on my primary machine, by applying https://github.com/Particular/NServiceBus.AmazonSQS/pull/125 everything works fine. Closing this for now.
