### ISSUE TITLE
Enable GitFlow

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AmazonSQS#98]
- [x] Create develop branch
- [x] [Bring in GitVersion](https://github.com/ahofman/NServiceBus.AmazonSQS/pull/100)

**Comment by danielmarbach** [comment]
Development branch is created and a PR is sent in to switch to GitVersion

**Comment by ahofman** [comment]
Thanks @danielmarbach , LGTM, merged the PR.
